// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ooapi.v5.core.Repositories;

#nullable disable

namespace ooapi.v5.core.Migrations
{
    [DbContext(typeof(CoreDBContext))]
    partial class CoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ooapiv5")
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ooapi.v5.Models.AcademicSession", b =>
                {
                    b.Property<Guid?>("AcademicSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicSessionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PrimaryCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Year")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AcademicSessionId");

                    b.HasIndex("PrimaryCodeId");

                    b.ToTable("AcademicSession", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.Address", b =>
                {
                    b.Property<Guid?>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AddressType")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComponentOfferingOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseOfferingOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GeolocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProgramOfferingOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ComponentOfferingOfferingId");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseOfferingOfferingId");

                    b.HasIndex("GeolocationId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("ProgramOfferingOfferingId");

                    b.ToTable("Address", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.Association", b =>
                {
                    b.Property<Guid>("AssociationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssociationType")
                        .HasColumnType("int");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RemoteState")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("AssociationId");

                    b.ToTable("Association", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.Author", b =>
                {
                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Author", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.Building", b =>
                {
                    b.Property<Guid?>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PrimaryCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BuildingId");

                    b.HasIndex("AddressId");

                    b.HasIndex("PrimaryCodeId");

                    b.ToTable("Building", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.Component", b =>
                {
                    b.Property<Guid?>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ComponentType")
                        .HasColumnType("int");

                    b.Property<Guid>("Course")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModeOfDelivery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Organization")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PrimaryCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeachingLanguage")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("ComponentId");

                    b.HasIndex("PrimaryCodeId");

                    b.ToTable("Component", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.ComponentOffering", b =>
                {
                    b.Property<Guid>("OfferingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnrollEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnrollStartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EnrolledNumberStudents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<decimal?>("MaxNumberStudents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinNumberStudents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModeOfDelivery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfferingType")
                        .HasColumnType("int");

                    b.Property<decimal?>("PendingNumberStudents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PrimaryCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("ResultExpected")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<int?>("ResultValueType")
                        .HasColumnType("int");

                    b.Property<int?>("ResultWeight")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("TeachingLanguage")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("OfferingId");

                    b.HasIndex("PrimaryCodeId");

                    b.ToTable("ComponentOffering", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.Consumer", b =>
                {
                    b.Property<Guid>("ConsumerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcademicSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssociationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComponentOfferingOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseOfferingOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EducationSpecificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NewsFeedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NewsItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProgramOfferingOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConsumerId");

                    b.HasIndex("AcademicSessionId");

                    b.HasIndex("AssociationId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ComponentOfferingOfferingId");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseOfferingOfferingId");

                    b.HasIndex("EducationSpecificationId");

                    b.HasIndex("GroupId");

                    b.HasIndex("NewsFeedId");

                    b.HasIndex("NewsItemId");

                    b.HasIndex("OfferingId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("ProgramOfferingOfferingId");

                    b.HasIndex("RoomId");

                    b.ToTable("Consumer", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.Cost", b =>
                {
                    b.Property<Guid>("CostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AmountWithoutVat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ComponentOfferingOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CourseOfferingOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProgramOfferingOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VatAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CostId");

                    b.HasIndex("ComponentOfferingOfferingId");

                    b.HasIndex("CourseOfferingOfferingId");

                    b.HasIndex("ProgramOfferingOfferingId");

                    b.ToTable("Cost", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldsOfStudy")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime?>("FirstStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ModeOfDelivery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PrimaryCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudyLoadProgramResultStudyLoadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeachingLanguage")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("CourseId");

                    b.HasIndex("PrimaryCodeId");

                    b.HasIndex("StudyLoadProgramResultStudyLoadId");

                    b.ToTable("Course", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.CourseOffering", b =>
                {
                    b.Property<Guid>("OfferingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnrollEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnrollStartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EnrolledNumberStudents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FlexibleEntryPeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FlexibleEntryPeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<decimal?>("MaxNumberStudents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinNumberStudents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModeOfDelivery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfferingType")
                        .HasColumnType("int");

                    b.Property<decimal?>("PendingNumberStudents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PrimaryCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("ResultExpected")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<int?>("ResultValueType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("TeachingLanguage")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("OfferingId");

                    b.HasIndex("PrimaryCodeId");

                    b.ToTable("CourseOffering", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.EducationSpecification", b =>
                {
                    b.Property<Guid>("EducationSpecificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("EducationSpecificationType")
                        .HasColumnType("int");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldsOfStudy")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int?>("FormalDocument")
                        .HasColumnType("int");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("LevelOfQualification")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("PrimaryCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Sector")
                        .HasColumnType("int");

                    b.Property<Guid>("StudyLoadProgramResultStudyLoadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("EducationSpecificationId");

                    b.HasIndex("PrimaryCodeId");

                    b.HasIndex("StudyLoadProgramResultStudyLoadId");

                    b.ToTable("EducationSpecification", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.Geolocation", b =>
                {
                    b.Property<Guid>("GeolocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Latitude")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .IsRequired()
                        .HasColumnType("float");

                    b.HasKey("GeolocationId");

                    b.ToTable("Geolocation", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.Group", b =>
                {
                    b.Property<Guid?>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupType")
                        .HasColumnType("int");

                    b.Property<Guid>("Organization")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PrimaryCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("GroupId");

                    b.HasIndex("PrimaryCodeId");

                    b.ToTable("Groups", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.LanguageOfChoice", b =>
                {
                    b.Property<Guid>("LanguageOfChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageOfChoiceId");

                    b.HasIndex("PersonId");

                    b.ToTable("LanguageOfChoice", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.LanguageTypedString", b =>
                {
                    b.Property<Guid>("LanguageTypedStringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcademicSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuildingId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComponentId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComponentId2")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComponentId3")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComponentOfferingOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComponentOfferingOfferingId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId2")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId3")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId4")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId5")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseOfferingOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseOfferingOfferingId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EducationSpecificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EducationSpecificationId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NewsFeedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NewsFeedId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NewsItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NewsItemId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OfferingId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrganizationId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProgramId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProgramId2")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProgramId3")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProgramId4")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProgramId5")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProgramOfferingOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProgramOfferingOfferingId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoomId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageTypedStringId");

                    b.HasIndex("AcademicSessionId");

                    b.HasIndex("AddressId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("BuildingId1");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ComponentId1");

                    b.HasIndex("ComponentId2");

                    b.HasIndex("ComponentId3");

                    b.HasIndex("ComponentOfferingOfferingId");

                    b.HasIndex("ComponentOfferingOfferingId1");

                    b.HasIndex("CostId");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseId1");

                    b.HasIndex("CourseId2");

                    b.HasIndex("CourseId3");

                    b.HasIndex("CourseId4");

                    b.HasIndex("CourseId5");

                    b.HasIndex("CourseOfferingOfferingId");

                    b.HasIndex("CourseOfferingOfferingId1");

                    b.HasIndex("EducationSpecificationId");

                    b.HasIndex("EducationSpecificationId1");

                    b.HasIndex("NewsFeedId");

                    b.HasIndex("NewsFeedId1");

                    b.HasIndex("NewsItemId");

                    b.HasIndex("NewsItemId1");

                    b.HasIndex("OfferingId");

                    b.HasIndex("OfferingId1");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationId1");

                    b.HasIndex("ProgramId");

                    b.HasIndex("ProgramId1");

                    b.HasIndex("ProgramId2");

                    b.HasIndex("ProgramId3");

                    b.HasIndex("ProgramId4");

                    b.HasIndex("ProgramId5");

                    b.HasIndex("ProgramOfferingOfferingId");

                    b.HasIndex("ProgramOfferingOfferingId1");

                    b.HasIndex("RoomId");

                    b.HasIndex("RoomId1");

                    b.ToTable("LanguageTypedString", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.NewsFeed", b =>
                {
                    b.Property<Guid>("NewsFeedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NewsFeedType")
                        .HasColumnType("int");

                    b.HasKey("NewsFeedId");

                    b.ToTable("NewsFeed", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.NewsItem", b =>
                {
                    b.Property<Guid>("NewsItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int?>("NewsItemType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("NewsItemId");

                    b.ToTable("NewsItem", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.Offering", b =>
                {
                    b.Property<Guid>("OfferingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnrollEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnrollStartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EnrolledNumberStudents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<decimal?>("MaxNumberStudents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinNumberStudents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModeOfDelivery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfferingType")
                        .HasColumnType("int");

                    b.Property<decimal?>("PendingNumberStudents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PrimaryCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("ResultExpected")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<int?>("ResultValueType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("TeachingLanguage")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("OfferingId");

                    b.HasIndex("PrimaryCodeId");

                    b.ToTable("Offering", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.Organization", b =>
                {
                    b.Property<Guid?>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("OrganizationType")
                        .HasColumnType("int");

                    b.Property<Guid>("PrimaryCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("OrganizationId");

                    b.HasIndex("PrimaryCodeId");

                    b.ToTable("Organization", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.OtherCodes", b =>
                {
                    b.Property<Guid>("OtherCodesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcademicSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComponentOfferingOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseOfferingOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EducationSpecificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProgramOfferingOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OtherCodesId");

                    b.HasIndex("AcademicSessionId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ComponentOfferingOfferingId");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseOfferingOfferingId");

                    b.HasIndex("EducationSpecificationId");

                    b.HasIndex("GroupId");

                    b.HasIndex("OfferingId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("ProgramOfferingOfferingId");

                    b.HasIndex("RoomId");

                    b.ToTable("OtherCodes", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("ActiveEnrollment")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Affiliations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfNationality")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ICEName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ICEPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("ICERelation")
                        .HasColumnType("int");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoOfficial")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PhotoSocial")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("PrimaryCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecondaryMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SurnamePrefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TitlePrefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleSuffix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.HasIndex("AddressId");

                    b.HasIndex("PrimaryCodeId");

                    b.ToTable("Person", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.PrimaryCode", b =>
                {
                    b.Property<Guid>("PrimaryCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrimaryCodeId");

                    b.ToTable("PrimaryCode", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.Program", b =>
                {
                    b.Property<Guid>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldsOfStudy")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime?>("FirstStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("LevelOfQualification")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ModeOfDelivery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModeOfStudy")
                        .HasColumnType("int");

                    b.Property<Guid>("PrimaryCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProgramType")
                        .HasColumnType("int");

                    b.Property<int?>("QualificationAwarded")
                        .HasColumnType("int");

                    b.Property<int?>("Sector")
                        .HasColumnType("int");

                    b.Property<Guid>("StudyLoadProgramResultStudyLoadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeachingLanguage")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("ProgramId");

                    b.HasIndex("PrimaryCodeId");

                    b.HasIndex("StudyLoadProgramResultStudyLoadId");

                    b.ToTable("Program", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.ProgramOffering", b =>
                {
                    b.Property<Guid>("OfferingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnrollEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnrollStartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EnrolledNumberStudents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FlexibleEntryPeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FlexibleEntryPeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<decimal?>("MaxNumberStudents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinNumberStudents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModeOfDelivery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfferingType")
                        .HasColumnType("int");

                    b.Property<decimal?>("PendingNumberStudents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PrimaryCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("ResultExpected")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<int?>("ResultValueType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("TeachingLanguage")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("OfferingId");

                    b.HasIndex("PrimaryCodeId");

                    b.ToTable("ProgramOffering", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.ProgramResultStudyLoad", b =>
                {
                    b.Property<Guid>("ProgramResultStudyLoadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("StudyLoadUnit")
                        .HasColumnType("int");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProgramResultStudyLoadId");

                    b.ToTable("ProgramResultStudyLoad", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.Resource", b =>
                {
                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Resource", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.Room", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<Guid>("Building")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GeolocationRoomGeolocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PrimaryCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoomType")
                        .HasColumnType("int");

                    b.Property<int?>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<string>("Wing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomId");

                    b.HasIndex("GeolocationRoomGeolocationId");

                    b.HasIndex("PrimaryCodeId");

                    b.ToTable("Room", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.RoomGeolocation", b =>
                {
                    b.Property<Guid>("RoomGeolocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Latitude")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .IsRequired()
                        .HasColumnType("float");

                    b.HasKey("RoomGeolocationId");

                    b.ToTable("RoomGeolocation", "ooapiv5");
                });

            modelBuilder.Entity("System.Collections.Generic.List<ooapi.v5.Models.LanguageTypedString>", b =>
                {
                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.ToTable("List<LanguageTypedString>", "ooapiv5");
                });

            modelBuilder.Entity("System.Collections.Generic.List<string>", b =>
                {
                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.ToTable("List<string>", "ooapiv5");
                });

            modelBuilder.Entity("ooapi.v5.Models.AcademicSession", b =>
                {
                    b.HasOne("ooapi.v5.Models.PrimaryCode", "PrimaryCode")
                        .WithMany()
                        .HasForeignKey("PrimaryCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryCode");
                });

            modelBuilder.Entity("ooapi.v5.Models.Address", b =>
                {
                    b.HasOne("ooapi.v5.Models.Component", null)
                        .WithMany("Addresses")
                        .HasForeignKey("ComponentId");

                    b.HasOne("ooapi.v5.Models.ComponentOffering", null)
                        .WithMany("Addresses")
                        .HasForeignKey("ComponentOfferingOfferingId");

                    b.HasOne("ooapi.v5.Models.Course", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CourseId");

                    b.HasOne("ooapi.v5.Models.CourseOffering", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CourseOfferingOfferingId");

                    b.HasOne("ooapi.v5.Models.Geolocation", "Geolocation")
                        .WithMany()
                        .HasForeignKey("GeolocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ooapi.v5.Models.Organization", null)
                        .WithMany("Addresses")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("ooapi.v5.Models.Program", null)
                        .WithMany("Addresses")
                        .HasForeignKey("ProgramId");

                    b.HasOne("ooapi.v5.Models.ProgramOffering", null)
                        .WithMany("Addresses")
                        .HasForeignKey("ProgramOfferingOfferingId");

                    b.Navigation("Geolocation");
                });

            modelBuilder.Entity("ooapi.v5.Models.Building", b =>
                {
                    b.HasOne("ooapi.v5.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ooapi.v5.Models.PrimaryCode", "PrimaryCode")
                        .WithMany()
                        .HasForeignKey("PrimaryCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("PrimaryCode");
                });

            modelBuilder.Entity("ooapi.v5.Models.Component", b =>
                {
                    b.HasOne("ooapi.v5.Models.PrimaryCode", "PrimaryCode")
                        .WithMany()
                        .HasForeignKey("PrimaryCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryCode");
                });

            modelBuilder.Entity("ooapi.v5.Models.ComponentOffering", b =>
                {
                    b.HasOne("ooapi.v5.Models.PrimaryCode", "PrimaryCode")
                        .WithMany()
                        .HasForeignKey("PrimaryCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryCode");
                });

            modelBuilder.Entity("ooapi.v5.Models.Consumer", b =>
                {
                    b.HasOne("ooapi.v5.Models.AcademicSession", null)
                        .WithMany("Consumers")
                        .HasForeignKey("AcademicSessionId");

                    b.HasOne("ooapi.v5.Models.Association", null)
                        .WithMany("Consumers")
                        .HasForeignKey("AssociationId");

                    b.HasOne("ooapi.v5.Models.Building", null)
                        .WithMany("Consumers")
                        .HasForeignKey("BuildingId");

                    b.HasOne("ooapi.v5.Models.Component", null)
                        .WithMany("Consumers")
                        .HasForeignKey("ComponentId");

                    b.HasOne("ooapi.v5.Models.ComponentOffering", null)
                        .WithMany("Consumers")
                        .HasForeignKey("ComponentOfferingOfferingId");

                    b.HasOne("ooapi.v5.Models.Course", null)
                        .WithMany("Consumers")
                        .HasForeignKey("CourseId");

                    b.HasOne("ooapi.v5.Models.CourseOffering", null)
                        .WithMany("Consumers")
                        .HasForeignKey("CourseOfferingOfferingId");

                    b.HasOne("ooapi.v5.Models.EducationSpecification", null)
                        .WithMany("Consumers")
                        .HasForeignKey("EducationSpecificationId");

                    b.HasOne("ooapi.v5.Models.Group", null)
                        .WithMany("Consumers")
                        .HasForeignKey("GroupId");

                    b.HasOne("ooapi.v5.Models.NewsFeed", null)
                        .WithMany("Consumers")
                        .HasForeignKey("NewsFeedId");

                    b.HasOne("ooapi.v5.Models.NewsItem", null)
                        .WithMany("Consumers")
                        .HasForeignKey("NewsItemId");

                    b.HasOne("ooapi.v5.Models.Offering", null)
                        .WithMany("Consumers")
                        .HasForeignKey("OfferingId");

                    b.HasOne("ooapi.v5.Models.Organization", null)
                        .WithMany("Consumers")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("ooapi.v5.Models.Person", null)
                        .WithMany("Consumers")
                        .HasForeignKey("PersonId");

                    b.HasOne("ooapi.v5.Models.Program", null)
                        .WithMany("Consumers")
                        .HasForeignKey("ProgramId");

                    b.HasOne("ooapi.v5.Models.ProgramOffering", null)
                        .WithMany("Consumers")
                        .HasForeignKey("ProgramOfferingOfferingId");

                    b.HasOne("ooapi.v5.Models.Room", null)
                        .WithMany("Consumers")
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("ooapi.v5.Models.Cost", b =>
                {
                    b.HasOne("ooapi.v5.Models.ComponentOffering", null)
                        .WithMany("PriceInformation")
                        .HasForeignKey("ComponentOfferingOfferingId");

                    b.HasOne("ooapi.v5.Models.CourseOffering", null)
                        .WithMany("PriceInformation")
                        .HasForeignKey("CourseOfferingOfferingId");

                    b.HasOne("ooapi.v5.Models.ProgramOffering", null)
                        .WithMany("PriceInformation")
                        .HasForeignKey("ProgramOfferingOfferingId");
                });

            modelBuilder.Entity("ooapi.v5.Models.Course", b =>
                {
                    b.HasOne("ooapi.v5.Models.PrimaryCode", "PrimaryCode")
                        .WithMany()
                        .HasForeignKey("PrimaryCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ooapi.v5.Models.ProgramResultStudyLoad", "StudyLoad")
                        .WithMany()
                        .HasForeignKey("StudyLoadProgramResultStudyLoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryCode");

                    b.Navigation("StudyLoad");
                });

            modelBuilder.Entity("ooapi.v5.Models.CourseOffering", b =>
                {
                    b.HasOne("ooapi.v5.Models.PrimaryCode", "PrimaryCode")
                        .WithMany()
                        .HasForeignKey("PrimaryCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryCode");
                });

            modelBuilder.Entity("ooapi.v5.Models.EducationSpecification", b =>
                {
                    b.HasOne("ooapi.v5.Models.PrimaryCode", "PrimaryCode")
                        .WithMany()
                        .HasForeignKey("PrimaryCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ooapi.v5.Models.ProgramResultStudyLoad", "StudyLoad")
                        .WithMany()
                        .HasForeignKey("StudyLoadProgramResultStudyLoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryCode");

                    b.Navigation("StudyLoad");
                });

            modelBuilder.Entity("ooapi.v5.Models.Group", b =>
                {
                    b.HasOne("ooapi.v5.Models.PrimaryCode", "PrimaryCode")
                        .WithMany()
                        .HasForeignKey("PrimaryCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryCode");
                });

            modelBuilder.Entity("ooapi.v5.Models.LanguageOfChoice", b =>
                {
                    b.HasOne("ooapi.v5.Models.Person", null)
                        .WithMany("LanguageOfChoice")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("ooapi.v5.Models.LanguageTypedString", b =>
                {
                    b.HasOne("ooapi.v5.Models.AcademicSession", null)
                        .WithMany("Name")
                        .HasForeignKey("AcademicSessionId");

                    b.HasOne("ooapi.v5.Models.Address", null)
                        .WithMany("Additional")
                        .HasForeignKey("AddressId");

                    b.HasOne("ooapi.v5.Models.Building", null)
                        .WithMany("Description")
                        .HasForeignKey("BuildingId");

                    b.HasOne("ooapi.v5.Models.Building", null)
                        .WithMany("Name")
                        .HasForeignKey("BuildingId1");

                    b.HasOne("ooapi.v5.Models.Component", null)
                        .WithMany("Assessment")
                        .HasForeignKey("ComponentId");

                    b.HasOne("ooapi.v5.Models.Component", null)
                        .WithMany("Description")
                        .HasForeignKey("ComponentId1");

                    b.HasOne("ooapi.v5.Models.Component", null)
                        .WithMany("Enrollment")
                        .HasForeignKey("ComponentId2");

                    b.HasOne("ooapi.v5.Models.Component", null)
                        .WithMany("Name")
                        .HasForeignKey("ComponentId3");

                    b.HasOne("ooapi.v5.Models.ComponentOffering", null)
                        .WithMany("Description")
                        .HasForeignKey("ComponentOfferingOfferingId");

                    b.HasOne("ooapi.v5.Models.ComponentOffering", null)
                        .WithMany("Name")
                        .HasForeignKey("ComponentOfferingOfferingId1");

                    b.HasOne("ooapi.v5.Models.Cost", null)
                        .WithMany("DisplayAmount")
                        .HasForeignKey("CostId");

                    b.HasOne("ooapi.v5.Models.Course", null)
                        .WithMany("AdmissionRequirements")
                        .HasForeignKey("CourseId");

                    b.HasOne("ooapi.v5.Models.Course", null)
                        .WithMany("Assessment")
                        .HasForeignKey("CourseId1");

                    b.HasOne("ooapi.v5.Models.Course", null)
                        .WithMany("Description")
                        .HasForeignKey("CourseId2");

                    b.HasOne("ooapi.v5.Models.Course", null)
                        .WithMany("Enrollment")
                        .HasForeignKey("CourseId3");

                    b.HasOne("ooapi.v5.Models.Course", null)
                        .WithMany("Name")
                        .HasForeignKey("CourseId4");

                    b.HasOne("ooapi.v5.Models.Course", null)
                        .WithMany("QualificationRequirements")
                        .HasForeignKey("CourseId5");

                    b.HasOne("ooapi.v5.Models.CourseOffering", null)
                        .WithMany("Description")
                        .HasForeignKey("CourseOfferingOfferingId");

                    b.HasOne("ooapi.v5.Models.CourseOffering", null)
                        .WithMany("Name")
                        .HasForeignKey("CourseOfferingOfferingId1");

                    b.HasOne("ooapi.v5.Models.EducationSpecification", null)
                        .WithMany("Description")
                        .HasForeignKey("EducationSpecificationId");

                    b.HasOne("ooapi.v5.Models.EducationSpecification", null)
                        .WithMany("Name")
                        .HasForeignKey("EducationSpecificationId1");

                    b.HasOne("ooapi.v5.Models.NewsFeed", null)
                        .WithMany("Description")
                        .HasForeignKey("NewsFeedId");

                    b.HasOne("ooapi.v5.Models.NewsFeed", null)
                        .WithMany("Name")
                        .HasForeignKey("NewsFeedId1");

                    b.HasOne("ooapi.v5.Models.NewsItem", null)
                        .WithMany("Content")
                        .HasForeignKey("NewsItemId");

                    b.HasOne("ooapi.v5.Models.NewsItem", null)
                        .WithMany("Name")
                        .HasForeignKey("NewsItemId1");

                    b.HasOne("ooapi.v5.Models.Offering", null)
                        .WithMany("Description")
                        .HasForeignKey("OfferingId");

                    b.HasOne("ooapi.v5.Models.Offering", null)
                        .WithMany("Name")
                        .HasForeignKey("OfferingId1");

                    b.HasOne("ooapi.v5.Models.Organization", null)
                        .WithMany("Description")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("ooapi.v5.Models.Organization", null)
                        .WithMany("Name")
                        .HasForeignKey("OrganizationId1");

                    b.HasOne("ooapi.v5.Models.Program", null)
                        .WithMany("AdmissionRequirements")
                        .HasForeignKey("ProgramId");

                    b.HasOne("ooapi.v5.Models.Program", null)
                        .WithMany("Assessment")
                        .HasForeignKey("ProgramId1");

                    b.HasOne("ooapi.v5.Models.Program", null)
                        .WithMany("Description")
                        .HasForeignKey("ProgramId2");

                    b.HasOne("ooapi.v5.Models.Program", null)
                        .WithMany("Enrollment")
                        .HasForeignKey("ProgramId3");

                    b.HasOne("ooapi.v5.Models.Program", null)
                        .WithMany("Name")
                        .HasForeignKey("ProgramId4");

                    b.HasOne("ooapi.v5.Models.Program", null)
                        .WithMany("QualificationRequirements")
                        .HasForeignKey("ProgramId5");

                    b.HasOne("ooapi.v5.Models.ProgramOffering", null)
                        .WithMany("Description")
                        .HasForeignKey("ProgramOfferingOfferingId");

                    b.HasOne("ooapi.v5.Models.ProgramOffering", null)
                        .WithMany("Name")
                        .HasForeignKey("ProgramOfferingOfferingId1");

                    b.HasOne("ooapi.v5.Models.Room", null)
                        .WithMany("Description")
                        .HasForeignKey("RoomId");

                    b.HasOne("ooapi.v5.Models.Room", null)
                        .WithMany("Name")
                        .HasForeignKey("RoomId1");
                });

            modelBuilder.Entity("ooapi.v5.Models.Offering", b =>
                {
                    b.HasOne("ooapi.v5.Models.PrimaryCode", "PrimaryCode")
                        .WithMany()
                        .HasForeignKey("PrimaryCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryCode");
                });

            modelBuilder.Entity("ooapi.v5.Models.Organization", b =>
                {
                    b.HasOne("ooapi.v5.Models.PrimaryCode", "PrimaryCode")
                        .WithMany()
                        .HasForeignKey("PrimaryCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryCode");
                });

            modelBuilder.Entity("ooapi.v5.Models.OtherCodes", b =>
                {
                    b.HasOne("ooapi.v5.Models.AcademicSession", null)
                        .WithMany("OtherCodes")
                        .HasForeignKey("AcademicSessionId");

                    b.HasOne("ooapi.v5.Models.Building", null)
                        .WithMany("OtherCodes")
                        .HasForeignKey("BuildingId");

                    b.HasOne("ooapi.v5.Models.Component", null)
                        .WithMany("OtherCodes")
                        .HasForeignKey("ComponentId");

                    b.HasOne("ooapi.v5.Models.ComponentOffering", null)
                        .WithMany("OtherCodes")
                        .HasForeignKey("ComponentOfferingOfferingId");

                    b.HasOne("ooapi.v5.Models.Course", null)
                        .WithMany("OtherCodes")
                        .HasForeignKey("CourseId");

                    b.HasOne("ooapi.v5.Models.CourseOffering", null)
                        .WithMany("OtherCodes")
                        .HasForeignKey("CourseOfferingOfferingId");

                    b.HasOne("ooapi.v5.Models.EducationSpecification", null)
                        .WithMany("OtherCodes")
                        .HasForeignKey("EducationSpecificationId");

                    b.HasOne("ooapi.v5.Models.Group", null)
                        .WithMany("OtherCodes")
                        .HasForeignKey("GroupId");

                    b.HasOne("ooapi.v5.Models.Offering", null)
                        .WithMany("OtherCodes")
                        .HasForeignKey("OfferingId");

                    b.HasOne("ooapi.v5.Models.Organization", null)
                        .WithMany("OtherCodes")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("ooapi.v5.Models.Person", null)
                        .WithMany("OtherCodes")
                        .HasForeignKey("PersonId");

                    b.HasOne("ooapi.v5.Models.Program", null)
                        .WithMany("OtherCodes")
                        .HasForeignKey("ProgramId");

                    b.HasOne("ooapi.v5.Models.ProgramOffering", null)
                        .WithMany("OtherCodes")
                        .HasForeignKey("ProgramOfferingOfferingId");

                    b.HasOne("ooapi.v5.Models.Room", null)
                        .WithMany("OtherCodes")
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("ooapi.v5.Models.Person", b =>
                {
                    b.HasOne("ooapi.v5.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ooapi.v5.Models.PrimaryCode", "PrimaryCode")
                        .WithMany()
                        .HasForeignKey("PrimaryCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("PrimaryCode");
                });

            modelBuilder.Entity("ooapi.v5.Models.Program", b =>
                {
                    b.HasOne("ooapi.v5.Models.PrimaryCode", "PrimaryCode")
                        .WithMany()
                        .HasForeignKey("PrimaryCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ooapi.v5.Models.ProgramResultStudyLoad", "StudyLoad")
                        .WithMany()
                        .HasForeignKey("StudyLoadProgramResultStudyLoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryCode");

                    b.Navigation("StudyLoad");
                });

            modelBuilder.Entity("ooapi.v5.Models.ProgramOffering", b =>
                {
                    b.HasOne("ooapi.v5.Models.PrimaryCode", "PrimaryCode")
                        .WithMany()
                        .HasForeignKey("PrimaryCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryCode");
                });

            modelBuilder.Entity("ooapi.v5.Models.Room", b =>
                {
                    b.HasOne("ooapi.v5.Models.RoomGeolocation", "Geolocation")
                        .WithMany()
                        .HasForeignKey("GeolocationRoomGeolocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ooapi.v5.Models.PrimaryCode", "PrimaryCode")
                        .WithMany()
                        .HasForeignKey("PrimaryCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Geolocation");

                    b.Navigation("PrimaryCode");
                });

            modelBuilder.Entity("ooapi.v5.Models.AcademicSession", b =>
                {
                    b.Navigation("Consumers");

                    b.Navigation("Name");

                    b.Navigation("OtherCodes");
                });

            modelBuilder.Entity("ooapi.v5.Models.Address", b =>
                {
                    b.Navigation("Additional");
                });

            modelBuilder.Entity("ooapi.v5.Models.Association", b =>
                {
                    b.Navigation("Consumers");
                });

            modelBuilder.Entity("ooapi.v5.Models.Building", b =>
                {
                    b.Navigation("Consumers");

                    b.Navigation("Description");

                    b.Navigation("Name");

                    b.Navigation("OtherCodes");
                });

            modelBuilder.Entity("ooapi.v5.Models.Component", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Assessment");

                    b.Navigation("Consumers");

                    b.Navigation("Description");

                    b.Navigation("Enrollment");

                    b.Navigation("Name");

                    b.Navigation("OtherCodes");
                });

            modelBuilder.Entity("ooapi.v5.Models.ComponentOffering", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Consumers");

                    b.Navigation("Description");

                    b.Navigation("Name");

                    b.Navigation("OtherCodes");

                    b.Navigation("PriceInformation");
                });

            modelBuilder.Entity("ooapi.v5.Models.Cost", b =>
                {
                    b.Navigation("DisplayAmount");
                });

            modelBuilder.Entity("ooapi.v5.Models.Course", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("AdmissionRequirements");

                    b.Navigation("Assessment");

                    b.Navigation("Consumers");

                    b.Navigation("Description");

                    b.Navigation("Enrollment");

                    b.Navigation("Name");

                    b.Navigation("OtherCodes");

                    b.Navigation("QualificationRequirements");
                });

            modelBuilder.Entity("ooapi.v5.Models.CourseOffering", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Consumers");

                    b.Navigation("Description");

                    b.Navigation("Name");

                    b.Navigation("OtherCodes");

                    b.Navigation("PriceInformation");
                });

            modelBuilder.Entity("ooapi.v5.Models.EducationSpecification", b =>
                {
                    b.Navigation("Consumers");

                    b.Navigation("Description");

                    b.Navigation("Name");

                    b.Navigation("OtherCodes");
                });

            modelBuilder.Entity("ooapi.v5.Models.Group", b =>
                {
                    b.Navigation("Consumers");

                    b.Navigation("OtherCodes");
                });

            modelBuilder.Entity("ooapi.v5.Models.NewsFeed", b =>
                {
                    b.Navigation("Consumers");

                    b.Navigation("Description");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("ooapi.v5.Models.NewsItem", b =>
                {
                    b.Navigation("Consumers");

                    b.Navigation("Content");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("ooapi.v5.Models.Offering", b =>
                {
                    b.Navigation("Consumers");

                    b.Navigation("Description");

                    b.Navigation("Name");

                    b.Navigation("OtherCodes");
                });

            modelBuilder.Entity("ooapi.v5.Models.Organization", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Consumers");

                    b.Navigation("Description");

                    b.Navigation("Name");

                    b.Navigation("OtherCodes");
                });

            modelBuilder.Entity("ooapi.v5.Models.Person", b =>
                {
                    b.Navigation("Consumers");

                    b.Navigation("LanguageOfChoice");

                    b.Navigation("OtherCodes");
                });

            modelBuilder.Entity("ooapi.v5.Models.Program", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("AdmissionRequirements");

                    b.Navigation("Assessment");

                    b.Navigation("Consumers");

                    b.Navigation("Description");

                    b.Navigation("Enrollment");

                    b.Navigation("Name");

                    b.Navigation("OtherCodes");

                    b.Navigation("QualificationRequirements");
                });

            modelBuilder.Entity("ooapi.v5.Models.ProgramOffering", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Consumers");

                    b.Navigation("Description");

                    b.Navigation("Name");

                    b.Navigation("OtherCodes");

                    b.Navigation("PriceInformation");
                });

            modelBuilder.Entity("ooapi.v5.Models.Room", b =>
                {
                    b.Navigation("Consumers");

                    b.Navigation("Description");

                    b.Navigation("Name");

                    b.Navigation("OtherCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
