using System.Text.Json.Nodes;
using OEAPI.Infrastructure.Query.Fields;
using Xunit;

namespace OEAPI.Infrastructure.Tests.Query.Fields;

/// <summary>
///     Tests <see cref="FieldPruner" /> against the real spec-derived required-field data (see
///     <see cref="SpecFieldRequirements" />, generated by <c>scripts/extract-spec-manifest.py</c>) using
///     the real <c>Organisation</c> schema - required: <c>organisationId</c>, <c>organisationType</c>,
///     <c>name</c>, <c>primaryCode</c>; optional: e.g. <c>shortName</c>. <c>Organisation.parent</c> is
///     itself an <c>Organisation</c>, used for the nested-selection cases.
/// </summary>
public class FieldPrunerTests
{
    [Fact]
    public void Prune_RequiredFieldNotExplicitlySelected_Survives()
    {
        JsonNode node = new JsonObject
        {
            ["organisationId"] = "org-1",
            ["primaryCode"] = "PC-1",
            ["shortName"] = "Org"
        };
        FieldSelection selection = FieldSelectionParser.Parse("(primaryCode)")!;

        FieldPruner.Prune(node, selection, "Organisation");

        Assert.True(node.AsObject().ContainsKey("organisationId"));
    }

    [Fact]
    public void Prune_ExplicitlyRequestedField_Survives()
    {
        JsonNode node = new JsonObject { ["organisationId"] = "org-1", ["primaryCode"] = "PC-1" };
        FieldSelection selection = FieldSelectionParser.Parse("(primaryCode)")!;

        FieldPruner.Prune(node, selection, "Organisation");

        Assert.True(node.AsObject().ContainsKey("primaryCode"));
    }

    [Fact]
    public void Prune_OptionalFieldNotSelected_IsRemoved()
    {
        JsonNode node = new JsonObject { ["organisationId"] = "org-1", ["shortName"] = "Org" };
        FieldSelection selection = FieldSelectionParser.Parse("(organisationId)")!;

        FieldPruner.Prune(node, selection, "Organisation");

        Assert.False(node.AsObject().ContainsKey("shortName"));
    }

    [Fact]
    public void Prune_UnknownSchemaName_OnlyExplicitSelectionSurvives()
    {
        JsonNode node = new JsonObject { ["organisationId"] = "org-1", ["primaryCode"] = "PC-1" };
        FieldSelection selection = FieldSelectionParser.Parse("(primaryCode)")!;

        FieldPruner.Prune(node, selection, "NotARealSchema");

        Assert.False(node.AsObject().ContainsKey("organisationId"));
        Assert.True(node.AsObject().ContainsKey("primaryCode"));
    }

    [Fact]
    public void Prune_NestedSelection_UsesNestedSchemaOwnRequiredFields()
    {
        JsonNode node = new JsonObject
        {
            ["organisationId"] = "org-1",
            ["parent"] = new JsonObject
            {
                ["organisationId"] = "org-parent",
                ["primaryCode"] = "PC-PARENT",
                ["shortName"] = "Parent Org"
            }
        };
        FieldSelection selection = FieldSelectionParser.Parse("(parent(primaryCode))")!;

        FieldPruner.Prune(node, selection, "Organisation");

        JsonObject parent = node["parent"]!.AsObject();
        Assert.True(parent.ContainsKey("organisationId"), "nested object's own required field must survive");
        Assert.True(parent.ContainsKey("primaryCode"), "nested object's explicitly requested field must survive");
        Assert.False(parent.ContainsKey("shortName"), "nested object's unrequested optional field must be pruned");
    }

    [Fact]
    public void Prune_ArrayOfObjects_AppliesSameSchemaToEveryItem()
    {
        JsonNode node = new JsonArray
        {
            new JsonObject { ["organisationId"] = "org-1", ["shortName"] = "One" },
            new JsonObject { ["organisationId"] = "org-2", ["shortName"] = "Two" }
        };
        FieldSelection selection = FieldSelectionParser.Parse("(organisationId)")!;

        FieldPruner.Prune(node, selection, "Organisation");

        Assert.All(node.AsArray(), item =>
        {
            Assert.True(item!.AsObject().ContainsKey("organisationId"));
            Assert.False(item.AsObject().ContainsKey("shortName"));
        });
    }
}
