/*
 * Open Education API
 *
 * OpenAPI (fka Swagger) specification for the Open Education API.  <figure>  <a target=\"_blank\" href=\"OOAPIv5_model.png\">   <img src=\"OOAPIv5_model.png\" alt=\"OOAPI information model that feeds OOAPI specification\" width=\"70%\" class=\"img-responsive\">   </a>   <figcaption> OOAPI information model that feeds OOAPI specification (click to enlage)</figcaption> </figure>  The model provides an overview of how the objects on which the API is specified are related. The overarching concept educations is not found in the in the end points of the API. The smaller concepts of programOffering, courseOffering and conceptOffering are all found in the offering endpoint. The different types of association can all be found in the association endpoint.  The original file for this model can be found <a target=\"_blank\" href=\"OOAPIv5_model_v0.4.drawio\">here</a>  The program relations object is not found as a separate endpoint but relations between programs can be found within the program endpoint by expanding that endpoint.  Information about earlier meetings and presentations can be found <a target=\"_blank\" href=\"https://github.com/open-education-api/notulen\">here</a>  Information on the EDU-API model that was also used for this api is shown <a target=\"_blank\" href=\"eduapi.png\">here</a> 
 *
 * OpenAPI spec version: 5.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// The component type - test: tentamen - lecture: college - practical: practicum - tutorial: werkcollege - consultation: consultatie - project: project - workshop: workshop - excursion: excursie - independent study: zelfstudie - external: extern - skills training: vaardighedentraining 
        /// </summary>
        /// <value>The component type - test: tentamen - lecture: college - practical: practicum - tutorial: werkcollege - consultation: consultatie - project: project - workshop: workshop - excursion: excursie - independent study: zelfstudie - external: extern - skills training: vaardighedentraining </value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ComponentType
        {
            /// <summary>
            /// Enum TestEnum for test
            /// </summary>
            [EnumMember(Value = "test")]
            TestEnum = 0,
            /// <summary>
            /// Enum LectureEnum for lecture
            /// </summary>
            [EnumMember(Value = "lecture")]
            LectureEnum = 1,
            /// <summary>
            /// Enum PracticalEnum for practical
            /// </summary>
            [EnumMember(Value = "practical")]
            PracticalEnum = 2,
            /// <summary>
            /// Enum TutorialEnum for tutorial
            /// </summary>
            [EnumMember(Value = "tutorial")]
            TutorialEnum = 3,
            /// <summary>
            /// Enum ConsultationEnum for consultation
            /// </summary>
            [EnumMember(Value = "consultation")]
            ConsultationEnum = 4,
            /// <summary>
            /// Enum ProjectEnum for project
            /// </summary>
            [EnumMember(Value = "project")]
            ProjectEnum = 5,
            /// <summary>
            /// Enum WorkshopEnum for workshop
            /// </summary>
            [EnumMember(Value = "workshop")]
            WorkshopEnum = 6,
            /// <summary>
            /// Enum ExcursionEnum for excursion
            /// </summary>
            [EnumMember(Value = "excursion")]
            ExcursionEnum = 7,
            /// <summary>
            /// Enum IndependentStudyEnum for independent study
            /// </summary>
            [EnumMember(Value = "independent study")]
            IndependentStudyEnum = 8,
            /// <summary>
            /// Enum ExternalEnum for external
            /// </summary>
            [EnumMember(Value = "external")]
            ExternalEnum = 9,
            /// <summary>
            /// Enum SkillsTrainingEnum for skills training
            /// </summary>
            [EnumMember(Value = "skills training")]
            SkillsTrainingEnum = 10        }
}
