/*
 * Open Education API
 *
 * OpenAPI (fka Swagger) specification for the Open Education API.  <figure>  <a target=\"_blank\" href=\"OOAPIv5_model.png\">   <img src=\"OOAPIv5_model.png\" alt=\"OOAPI information model that feeds OOAPI specification\" width=\"70%\" class=\"img-responsive\">   </a>   <figcaption> OOAPI information model that feeds OOAPI specification (click to enlage)</figcaption> </figure>  The model provides an overview of how the objects on which the API is specified are related. The overarching concept educations is not found in the in the end points of the API. The smaller concepts of programOffering, courseOffering and conceptOffering are all found in the offering endpoint. The different types of association can all be found in the association endpoint.  The original file for this model can be found <a target=\"_blank\" href=\"OOAPIv5_model_v0.4.drawio\">here</a>  The program relations object is not found as a separate endpoint but relations between programs can be found within the program endpoint by expanding that endpoint.  Information about earlier meetings and presentations can be found <a target=\"_blank\" href=\"https://github.com/open-education-api/notulen\">here</a>  Information on the EDU-API model that was also used for this api is shown <a target=\"_blank\" href=\"eduapi.png\">here</a> 
 *
 * OpenAPI spec version: 5.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// The type of this organization. Each OOAPI endpoint should have a single organization with type `root`, describing the root organization. - root: the root of this organization, representing the Educational Institution itself - institute: instituut - department: departement - faculty: faculteit - branch: vestiging - academy: academie - school: school 
        /// </summary>
        /// <value>The type of this organization. Each OOAPI endpoint should have a single organization with type `root`, describing the root organization. - root: the root of this organization, representing the Educational Institution itself - institute: instituut - department: departement - faculty: faculteit - branch: vestiging - academy: academie - school: school </value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum OrganizationType
        {
            /// <summary>
            /// Enum RootEnum for root
            /// </summary>
            [EnumMember(Value = "root")]
            RootEnum = 0,
            /// <summary>
            /// Enum InstituteEnum for institute
            /// </summary>
            [EnumMember(Value = "institute")]
            InstituteEnum = 1,
            /// <summary>
            /// Enum DepartmentEnum for department
            /// </summary>
            [EnumMember(Value = "department")]
            DepartmentEnum = 2,
            /// <summary>
            /// Enum FacultyEnum for faculty
            /// </summary>
            [EnumMember(Value = "faculty")]
            FacultyEnum = 3,
            /// <summary>
            /// Enum BranchEnum for branch
            /// </summary>
            [EnumMember(Value = "branch")]
            BranchEnum = 4,
            /// <summary>
            /// Enum AcademyEnum for academy
            /// </summary>
            [EnumMember(Value = "academy")]
            AcademyEnum = 5,
            /// <summary>
            /// Enum SchoolEnum for school
            /// </summary>
            [EnumMember(Value = "school")]
            SchoolEnum = 6        }
}
